name: Docker Build and Push

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.ACCESS_CODE }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: kemsyt/my-image

      - name: Check Docker Buildx output
        run: echo "${{ steps.docker_build.outputs }}"

      - name: List Docker images
        run: docker images

      - name: Debug GitHub context
        run: echo "${{ toJson(github) }}"
