name: Check Docker Repository Existence

on:
  push:
    branches:
      - main

jobs:
  check_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Docker repository exists
        id: check_repo
        run: |
          REPO_NAME="my-image"
          USERNAME="your-dockerhub-username"
          response=$(curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/$USERNAME/$REPO_NAME/)
          if [ $response -eq 200 ]; then
            echo "Repository $REPO_NAME exists."
          elif [ $response -eq 404 ]; then
            echo "Repository $REPO_NAME does not exist."
          else
            echo "Failed to check repository existence with status code: $response"
            exit 1
          fi
